"use client";

import { decodeAiReview } from "@/lib/aiReview";
import { Card, CardHeader, CardBody, Badge, Notice } from "@/components/ui";

export function AIReviewDisplay({ aiReview }: { aiReview: `0x${string}` }) {
  const decoded = decodeAiReview(aiReview);
  if (!decoded) return null;

  const { raw, parsed } = decoded;

  return (
    <Card>
      <CardHeader
        title="AI review"
        subtitle="Generated by Ritual AI from all submissions."
        action={
          parsed ? (
            <Badge tone="accent">Recommends #{parsed.winnerIndex}</Badge>
          ) : (
            <Badge tone="amber">Unparsed</Badge>
          )
        }
      />
      <CardBody className="space-y-3">
        {parsed ? (
          <>
            {parsed.ranking.length > 0 && (
              <div className="overflow-hidden rounded-xl border border-white/10">
                <table className="w-full text-left text-sm">
                  <thead className="bg-white/5 text-xs uppercase tracking-wide text-zinc-400">
                    <tr>
                      <th className="px-3 py-2">#</th>
                      <th className="px-3 py-2">Score</th>
                      <th className="px-3 py-2">Reason</th>
                    </tr>
                  </thead>
                  <tbody>
                    {[...parsed.ranking]
                      .sort((a, b) => b.score - a.score)
                      .map((r) => (
                        <tr
                          key={r.index}
                          className={`border-t border-white/5 ${
                            r.index === parsed.winnerIndex
                              ? "bg-[var(--accent)]/10"
                              : ""
                          }`}
                        >
                          <td className="px-3 py-2 font-mono">
                            {r.index}
                            {r.index === parsed.winnerIndex && (
                              <svg className="inline-block w-3 h-3 ml-1 text-[var(--accent-light)]" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" /></svg>
                            )}
                          </td>
                          <td className="px-3 py-2 font-medium">{r.score}</td>
                          <td className="px-3 py-2 text-zinc-300">{r.reason}</td>
                        </tr>
                      ))}
                  </tbody>
                </table>
              </div>
            )}

            {parsed.summary && (
              <div className="rounded-xl bg-black/20 px-3 py-2 text-sm text-zinc-200">
                <span className="text-zinc-500">Summary: </span>
                {parsed.summary}
              </div>
            )}
          </>
        ) : (
          <>
            <Notice tone="amber">
              Couldn&apos;t parse the AI review as JSON. Showing the raw response.
            </Notice>
            <pre className="max-h-72 overflow-auto rounded-xl bg-black/40 p-3 font-mono text-xs text-zinc-300 whitespace-pre-wrap break-words">
              {raw}
            </pre>
          </>
        )}
      </CardBody>
    </Card>
  );
}
